name: date_range_dropdown
description: Set predefined date ranges with dropdown
version: 1.0.1
homepage: https://github.com/wendellrocha/date_range_dropdown

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true